config/routes.rb
LittleBooks::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  delete '/logout', to: 'sessions#destroy'
  # match '/logout', to: 'sessions#destroy'
  get '/fb' , to: 'facebook#fb'
  root :to => 'high_voltage/pages#show', id: "home"

  resources :stories do
    resources :mytales do
      get :print, :on => :member
      get :read, :on => :member
      get :email, :on => :member
      resources :mytale_images
    end
  end

  get '/images' => 'mytale_images#index', :as => :all_images

  get '/auth/facebook/callback' => 'facebook#create', :as => :facebook_login
  get '/auth/failure' => 'stories#index'
end

app/models/mytale_image.rb
class MytaleImage < ActiveRecord::Base
  attr_accessible :mytale_id, :people_image_id

  belongs_to :mytale
  belongs_to :people_image

  validates_presence_of :mytale_id, :people_image_id
end

app/controllers/mytale_images_controller.rb
class MytaleImagesController < ApplicationController
  include MytaleHelper

  def index
    get_images
  end

  def new
    get_images
    @mytale = Mytale.find_by_id(params[:mytale_id])
    @mycharacter = MytalesCharacter.find_by_id(@mytale.mytales_character_id)
  end

  def create
    @mytale = Mytale.find_by_id(params[:mytale_id])
    create_mytale_image
    if @myimage.save
      @mytale.update_attribute(:mytale_image_id, @myimage.id)
      redirect_to story_mytale_path(story_id: @mytale.story_id, id: @mytale.id)
    else
      @error = @myimage.errors.full_messages.join(". ")
      get_story_character
      get_genders
      @story_paged = @story.paged.slice!(5)
      render "stories/show", story_id: @mytale.story
    end
  end
end

app/views/mytale_images/index.html.erb
<h2>Available Characters</h2>

<div class="section">
<% @peopleimages.each do |image| %>
  <% if image.gender.sex == "female" %>
    <div class="col span_1_of_5">
      <%= image_tag(image.url) %>
    </div>
  <% end %>
<% end %>
</div>

<div class="section">
<% @peopleimages.each do |image| %>
  <% if image.gender.sex == "male" %>
    <div class="col span_1_of_5">
      <%= image_tag(image.url) %>
    </div>
  <% end %>
<% end %>
</div>

app/views/mytale_images/new.html.erb
<h1>
  What does <%= @mycharacter.name %> look like?
</h1>

<p>
  Select an image to finishing customizing <%= @mytale.title %>.
</p>


<div class="section">
<% @peopleimages.each do |image| %>
  <% if image.gender.sex == "female" %>
    <div class="col span_1_of_5">
      <%= link_to image_tag(image.url), story_mytale_mytale_images_path(people_image_id: image.id), mytale_id: params[:mytale_id], method: :post, :id => image.id %>
    </div>
  <% end %>
<% end %>
</div>

<div class="section">
<% @peopleimages.each do |image| %>
  <% if image.gender.sex == "male" %>
    <div class="col span_1_of_5">
      <%= link_to image_tag(image.url), story_mytale_mytale_images_path(people_image_id: image.id), mytale_id: params[:mytale_id], method: :post, :id => image.id %>
    </div>
  <% end %>
<% end %>
</div>