config/routes.rb
LittleBooks::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  delete '/logout', to: 'sessions#destroy'
  # match '/logout', to: 'sessions#destroy'
  get '/fb' , to: 'facebook#fb'
  root :to => 'high_voltage/pages#show', id: "home"

  resources :stories do
    resources :mytales do
      get :print, :on => :member
      get :read, :on => :member
      get :email, :on => :member
      resources :mytale_images
    end
  end

  get '/images' => 'mytale_images#index', :as => :all_images

  get '/auth/facebook/callback' => 'facebook#create', :as => :facebook_login
  get '/auth/failure' => 'stories#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password

  has_many :mytales
  has_many :stories, :through => :mytales
  has_many :mytale_images, :through => :mytales

  has_secure_password

  validates_uniqueness_of :email
  validates_presence_of :name, :email, :password
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  validates_length_of :name, :within => 2..20, :too_long => "must be less than 20 characters.", :too_short => "must be at least 2 characters."
  validates_length_of :password, :within => 6..15, :too_long => "must be less than 15 characters.", 
                      :too_short => "must be at least 6 characters."

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save(:validate=>false)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render "_new"
  end

  def create
    @user = User.new(params[:user])
    #@user.non_fb_signup = true
    if @user.save
      create_session
      UserMailer.welcome_signup(@user).deliver
      redirect_to @user
    else
      @error = @user.errors.full_messages.join(". ")
      render "_new"
    end
  end

  def show
    @user = User.find(params[:id])
    @mytales = @user.mytales
    @mytale = @mytales.first
  end
end

app/views/users/_new.html.erb
 <h1>
   Welcome to Little Books
 </h1>

 <h2 class="num-alt">
   <%= link_to "Log In with Facebook", '/auth/facebook' %>
   <%= link_to "Log In with Little Books", new_session_path %>
 </h2>

<h3>
  Or create a Little Books account:
</h3>
<%= render "shared/errors", layout: false %>

<%= form_for(:user, url: users_path) do |f| %>
<%= f.label :name, "Name" %><br>
<%= f.text_field :name, placeholder: 'Name'%>
<p>
<%= f.label :email, "Email" %><br>
<%= f.text_field :email, placeholder: 'me@email.com' %>
</p>
<%= f.label :password, "Password" %><br>
<%= f.password_field :password, placeholder: '********'%>
<p>
<%= f.submit "Sign Up" %>
</p>
<%end%>

app/views/users/show.html.erb
<% if is_user? %>
  <h1>
    Hello <%= @user.name %>
  </h1>
<% else %>
  <h1>
    <%= @user.name %>'s Profile
  </h1>
<% end %>

<% if @mytales.any? %>
  <% @mytales.each_with_index do |tale, num| %>
    <div class="section">
      <div class="col span_1_of_4">
        <p>
          <%= image_tag(tale.mytale_image.people_image.url) %>
        </p>
      </div>
      <div class="col span_3_of_4">
        <h2>
          <%= tale.title %>
        </h2>
        <span class="num-alt">
          <%= link_to "Read", read_story_mytale_path(story_id: tale.story, id: tale.id) %> <%= link_to "Print", print_story_mytale_path(story_id: tale.story, id: tale.id), class: "print-link" %>
          <% if is_owner? %>
          <%= link_to "Edit", edit_story_mytale_path(story_id: tale.story, id: tale.id) %><%= link_to "Delete", story_mytale_path(story_id: tale.story, id: tale.id), method: :delete %>
          <% end %>
        </span>
        <p>
          <%= tale.summary %>
        </p>
        <%= link_to "View story details", story_mytale_path(story_id: tale.story_id, id: tale.id) %>
      </div>
  </div>
<% end %>

<% else %>
  <% if is_user? %>
    <h2 class="num-alt">
      You haven't created any custom stories yet.
    </h2>
    <p class="num-alt">
      <%= link_to "Browse the library to begin customizing", stories_path %>
    </p>
  <% else %>
    <%= @user.name %> doesn't have any stories yet.
  <% end %>
<% end %>