config/routes.rb
LittleBooks::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  delete '/logout', to: 'sessions#destroy'
  # match '/logout', to: 'sessions#destroy'
  get '/fb' , to: 'facebook#fb'
  root :to => 'high_voltage/pages#show', id: "home"

  resources :stories do
    resources :mytales do
      get :print, :on => :member
      get :read, :on => :member
      get :email, :on => :member
      resources :mytale_images
    end
  end

  get '/images' => 'mytale_images#index', :as => :all_images

  get '/auth/facebook/callback' => 'facebook#create', :as => :facebook_login
  get '/auth/failure' => 'stories#index'
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :summary, :content, :title, :character_id, :source_link, :attribution, :character, :background_image

  has_many :mytales
  has_many :users, :through => :mytales
  belongs_to :character
  belongs_to :background_image

  slice :content, :as => :paged, :window => 2, :slice => { :maximum => 100, :complete => /(?<=\.\s)|(?<=\!\s)/ }

  validates_presence_of :title, :content, :summary, :character_id, :source_link, :attribution

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  include MytaleHelper

  def index
    @stories = Story.all
    get_genders
  end

  def show
    get_genders
    @story = Story.find(params[:id])
    @story_paged = @story.paged.slice!(5)
    @character = @story.character
    @mytale = Mytale.new
  end
end

app/views/stories/index.html.erb
<h1>
  Little Books Library
</h1>

<% @stories.each do |story| %>
  <div class="section">
    <div class="col span_1_of_2">
      <%= image_tag story.background_image.url, width: '90%' %>
    </div>
    <div class="col span_1_of_2">
      <h2>
        <%= story.title %>
      </h2>
      <p>
        <%= story.summary %>
      </p>


      <p class="num-alt">
        <%= link_to "Customize story", new_story_mytale_path(story.id) %>
      </p>
    </div>
  </div>
<% end %>

app/views/stories/indy1.html.erb
<% @stories.each_with_index do |story, num| %>
  <% if num == 0 || num % 2 == 0 %>
    <div class="section">
      <div class="col span_1_of_2">
        <h3><%= story.title %></h3>
        <%= story.summary %> <br>
        <%= link_to "Customize this story", new_story_mytale_path(story.id) %>
      </div>
  <% else %>
    <div class="col span_1_of_2">
      <h3><%= story.title %></h3>
      <%= story.summary %> <br>
      <%= link_to "Customize this story", new_story_mytale_path(story.id) %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/stories/show.html.erb
<%= render "shared/errors", layout: false %>

<%= render 'mytales/new' %>