config/routes.rb
LittleBooks::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  delete '/logout', to: 'sessions#destroy'
  # match '/logout', to: 'sessions#destroy'
  get '/fb' , to: 'facebook#fb'
  root :to => 'high_voltage/pages#show', id: "home"

  resources :stories do
    resources :mytales do
      get :print, :on => :member
      get :read, :on => :member
      get :email, :on => :member
      resources :mytale_images
    end
  end

  get '/images' => 'mytale_images#index', :as => :all_images

  get '/auth/facebook/callback' => 'facebook#create', :as => :facebook_login
  get '/auth/failure' => 'stories#index'
end

app/models/mytale.rb
class Mytale < ActiveRecord::Base
  attr_accessible :title, :summary, :content, :user, :story_id, :mytales_character_id, :mytale_image_id, :mytales_character, :mytale_image

  belongs_to :user
  belongs_to :story
  belongs_to :mytales_character
  belongs_to :mytale_image

  validates_presence_of :title, :content, :story_id, :mytales_character_id

  slice :content, :as => :page, :window => 0, :slice => { :maximum => 175, :complete => /(?<=\.\s)|(?<=\!\s)|(?<=\,\s)|(?<=\'\s)|(?<=\;\s)|(?<=\:\s)/ }
  slice :content, :as => :edit, :window => 0, :slice => { :maximum => 100, :complete => /(?<=\.\s)|(?<=\!\s)/ }

  def replace_text
    replace_main_char(/#{story.character.name}/, mytales_character.name)
    subber = subber_goldy

    if mytales_character.gender.sex != "female"
      subber.each {|female, male| content.gsub!(female, male)}
    end
  end

  def replace_main_char(currentchar, newchar)
    content.gsub!(/#{currentchar}/, newchar)
  end

  def subber_goldy
    {/\bmiss\b/ => "lad", /\bHer\b/ => "His", /\bherself\b/ => "himself",
            /\bher\b/ => "his", /\bShe\b/ => "He", /\bshe\b/ => "he", /\bprincess\b/ => "prince", /\bgirl\b/ => "boy", /\bPrincess\b/ => "Prince"}
  end
end

app/controllers/mytales_controller.rb
class MytalesController < ApplicationController
  include MytaleHelper

  def new
    get_story_character
    get_genders
    @mytale = Mytale.new
    @mytales_character = MytalesCharacter.new
    @story_paged = @story.paged.slice!(5)
    render "_new"
  end

  def create
    get_story_character
    create_mytales_character
    create_mytale
    if @mytale.save
      create_mytales_character_relationship
      redirect_to new_story_mytale_mytale_image_path(story_id: @story.id, mytale_id: @mytale.id)
    else
      render :new
    end
  end

  def edit
    @mytale = Mytale.find_by_id(params[:id])
    @mytales_character = MytalesCharacter.find_by_id(@mytale.mytales_character_id)
    get_story_character
    get_images
    get_genders
    if is_owner?
      render :edit
    else
      render "shared/denied"
    end
  end

  def update
    get_genders
    get_images
    get_story_character
    @mytale = Mytale.find_by_id(params[:id])
    @mytales_character = MytalesCharacter.find_by_id(@mytale.mytales_character_id)
    @myimage = MytaleImage.find_by_mytale_id(params[:id])
    update_all_mytales
    if @mytale.save && @mytales_character.save && @myimage.save
      redirect_to story_mytale_path(story_id: @story.id, mytale_id: @mytale.id)
    else
      render :edit
    end
  end

  def show
    @mytale = Mytale.find(params[:id])
    get_story_image
  end

  def destroy
    @mytale = Mytale.find(params[:id])
    if is_owner?
      @mytale.destroy
      redirect_to stories_path
    else
      render "shared/denied"
    end
  end

  def print
    @mytale = Mytale.find_by_id(params[:id])
    get_story_image
    render layout: "print"
  end

  def read
    @mytale = Mytale.find_by_id(params[:id])
    @story_paged = @mytale.page.slice!(params[:slice])
    get_story_image
    respond_to do |format|
      format.html { render layout: "read" }
      format.js {}
    end
  end

  def email
   @mytale = Mytale.find_by_id(params[:id])
   @story = Story.find_by_id(params[:story_id])
   @user = User.find_by_id(@mytale.user_id)
   #get_story_image
   #call action mailer here 
   UserMailer.email_story(@user,@mytale).deliver
   redirect_to story_mytale_path(story_id: @story.id, mytale_id: @mytale.id)
  end
end

app/helpers/mytale_helper.rb
module MytaleHelper
  def get_genders
    @gender = Gender.all
  end

  def get_images
    @peopleimages = PeopleImage.all
  end

  def get_story_image
    @image = PeopleImage.find_by_id(@mytale.mytale_image.people_image_id)
  end

  def get_story_character
    @story = Story.find_by_id(params[:story_id])
    @character = @story.character
  end

  def create_mytales_character
    @mytales_character = MytalesCharacter.create(name: params[:name], gender: Gender.find(params[:gender]), character: @story.character)
  end

  def create_mytale
    params[:mytale][:mytales_character_id] = @mytales_character.id
    @mytale = Mytale.new(params[:mytale])
    @mytale.replace_text
  end

  def create_mytales_character_relationship
    @mytales_character.update_attributes(mytale_id: @mytale.id)
    @mytale.update_attributes(user: current_user)
  end

  def create_mytale_image
    @myimage = MytaleImage.new(people_image_id: params[:people_image_id], mytale_id: params[:mytale_id])
  end

  def update_all_mytales
    @mytale.assign_attributes(params[:mytale])
    @mytales_character.assign_attributes(name: params[:name], gender: Gender.find(params[:gender]))
    @myimage.assign_attributes(people_image_id: params[:image_ids][0].to_i)
  end

end

app/views/mytales/_new.html.erb
<h1>
   Create your custom story
</h1>

<p class="center">
  <%= image_tag @story.background_image.url %>
</p>


<%= form_for ([@story, @mytale]) do |f| %>
  <div class="section">
    <div class="col span_1_of_3">
      <%= f.label :title, "Story title" %> <br>
      <%= f.text_field :title, value: "#{@story.title}", autofocus: true %>
    </div>

    <div class="col span_1_of_3">
      <%= label_tag :name, "Main character's name" %> <br>
      <%= text_field_tag :name, "", value: "#{@story.character.name}" %>
    </div>

    <div class="col span_1_of_3">
      <%= label_tag :gender, "Main character's gender" %> <br>
      <%= select_tag :gender, options_from_collection_for_select(@gender, "id", "sex"), { :prompt => 'Gender?', :include_blank => false } %>
    </div>
  </div>
  <div class="section">
    <span class="jsError"></span> <br>
    <%= f.button "Customize" %>
    <%= f.hidden_field :content, value: @story.content %>
    <%= f.hidden_field :story_id, value: @story.id %>
    <%= f.hidden_field :summary, value: @story.summary %>
    <h2 class="mytale-title"><%= @story.title %></h2>
    <p class="word-play">... <%= @story_paged%> ...</p>
  <% end %>
  </div>

app/views/mytales/_page.html.erb
 <div class="section">
  <div class="col span_1_of_7 num-alt xlarge center">
    <% if params[:slice] && params[:slice] != "1" %>
      <%= link_to "<", "?slice=#{params[:slice].to_i-1}", :remote => true %>
    <% end %>
  </div>
  <div class="col span_5_of_7">
      <div class="meter">
      <div class="progress center" style="width:<%= get_progress_percentage %>">
        <span class="xsmall">
          <% if params[:slice] && params[:slice] != "1" %>
            <%= params[:slice] %>
          <% end %>
        </span>
      </div>
    </div>
    <div class="reader">
    <%= @story_paged %>
  </div>
  </div>
  <div class="col span_1_of_7 num-alt xlarge center">
    <% if params[:slice] %>
      <%= link_to ">", "?slice=#{params[:slice].to_i+1}", :remote=> true %>
    <% else %>
      <%= link_to ">", "?slice=2", :remote=> true %>
    <% end %>
  </div>
</div>

<div class="section center small">
  <div class="col span_1_of_7"></div>
  <div class="col span_5_of_7">
    <% if params[:slice] && params[:slice] != "1" %>
      <%= link_to "Back to beginning", "?slice=1", :remote => true %>
      <% end %>
  </div>
  <div class="col span_1_of_7"></div>
</div>

app/views/mytales/edit.html.erb
<h1>
  Edit your story
</h1>

<h2>
  What does <%= @mytale.mytales_character.name %> look like?
</h2>

<div class="section">
  <div class="col span_1_of_4">
    <%= form_for ([@story, @mytale]) do |f| %>
    <h4>
      <%= @mytale.mytales_character.name %>'s current image:
    </h4>
    <%= image_tag (@mytale.mytale_image.people_image.url) %>
  </div>

  <div class="col span_3_of_4">
    <h4>Change <%= @mytale.mytales_character.name %> by selecting a new character below:</h4>
      <% @peopleimages.each do |image| %>
        <div class="col span_1_of_6">
          <%= image_tag image.url,  height: '105' %>
          <%= radio_button_tag 'image_ids[]', image.id, @mytale.mytale_image.people_image.id == image.id %>
        </div>
      <%end%>
  </div>
<p>&nbsp;</p>
<h2>
  Change <%= @mytale.title %>:
</h2>
  <div class="section">
    <div class="col span_1_of_3">
      <%= f.label :title, "Title" %> <br>
      <%= f.text_field :title, placeholder: "#{@mytale.title}" %>
    </div>

    <div class="col span_1_of_3">
      <%= label_tag :name, "Main Character Name" %> <br>
      <%= text_field_tag :name, "", value: "#{@mytales_character.name}", autofocus: true %>
    </div>

    <div class="col span_1_of_3">
      <%= label_tag :gender, "Gender" %> <br>
      <%= select_tag :gender, options_from_collection_for_select(@gender, "id", "sex", @mytale.mytales_character.gender.id)%>
    </div>
  </div>
  <div class="section">
    <%= f.hidden_field :content, value: @mytale.content %>
    <%= f.hidden_field :story_id, value: @mytale.story_id %>
    <%= f.hidden_field :summary, value: @mytale.summary %>
    <p class="word-play">... <%= @mytale.edit.slice!(5) %> ...</p>
    <%= f.button "Edit your story" %>
<%end%>

app/views/mytales/new.html.erb
<%= form_for ([@story, @mytale]) do |f| %>
  <div class="section">
    <div class="col span_1_of_3">
      <%= f.label :title, "Title" %> <br>
      <%= f.text_field :title, placeholder: "#{@story.title}" %>
    </div>

  <div class="col span_1_of_3">
      <%= label_tag :name, "Main Character Name" %> <br>
      <%= text_field_tag :name, "", placeholder: "#{@character.name}" %>
    </div>

    <div class="col span_1_of_3">
      <%= label_tag :gender, "Gender" %> <br>
      <%= select_tag :gender, options_from_collection_for_select(@gender, "id", "sex") %>
    </div>
  </div>
  <div class="section">
    <%= f.submit "Customize" %>
    <%= f.hidden_field :content, value: @story.content %>
    <%= f.hidden_field :story_id, value: @story.id %>
    <%= f.hidden_field :summary, value: @story.summary %>
  <% end %>
  </div>


<h2><%= @story.title %></h2>

<p>
  <%=@story.content%>
</p>

app/views/mytales/print.html.erb
<div class="section">
  <div class="col span_1_of_5">
    <%= link_to 'Print', '#', class: "print"%>
  </div>

  <div class="col span_3_of_5 center">
    <%= image_tag @mytale.story.background_image.url %>
    <div class="kid">
      <%= image_tag(@image.url) %>
    </div>
    <h1>
      <%= @mytale.title %>
    </h1>
    <p class="print-story">
      <%= @mytale.content %>
    </p>
  </div>

  <div class="col span_1_of_5">
    <!-- space -->
  </div>
</div>

app/views/mytales/read.html.erb
<div class="section">
  <div class="col span_1_of_5">
    <!-- Empty div for spacing -->
  </div>

  <div class="col span_3_of_5 center">
    <h2 class="center">
      <%= @mytale.title %>
    </h2>
    <%= image_tag @mytale.story.background_image.url, height: '350px' %>

    <div class="kid">
      <%= image_tag @image.url %>
    </div>
  </div>
  </div>
  <div class="col span_1_of_5 small read-menu">
       <ul class="read">
      <li class="read"><%= link_to "Home", root_path %></li>
      <li class="read"><%= link_to "Print", print_story_mytale_path(story_id: @mytale.story_id, id: @mytale.id), class: "print-link" %></li>
      <% if current_user %>
        <li class="read"><%= link_to "My profile", user_path(current_user.id) %></li>
      <% end %>
      <li class="read"><%= link_to "Story details", story_mytale_path(story_id: @mytale.story_id, id: @mytale.id) %></li>
    </ul>
  </div>
</div>

<div class="section">
  <div class="col span_1_of_5">
    <!-- Empty div for spacing -->
  </div>

  <div class="col span_3_of_5" id="paged-content">
      <%= render partial: "page" %>
  </div>

  <div class="col span_1_of_5">
    <!-- Empty div for spacing -->
  </div>
</div>

app/views/mytales/read.js.erb
$("#paged-content").empty();
$("#paged-content").append("<%= escape_javascript(render 'page', locals: {story_paged: @story_paged}) %>");

app/views/mytales/show.html.erb
<h1>
  <%= @mytale.title %>
</h1>

<div class="section">
  <div class="col span_2_of_3">
    <p>
      <%= @mytale.story.summary %>
    </p>
    <span class="num-alt large">
      <%= link_to "Read story now!", read_story_mytale_path(story_id: @mytale.story_id, id: @mytale.id) %>
    </span>

    <h3>
      Additional Options
    </h3>

    <p class="num-alt">
      <%= link_to "Print full story", print_story_mytale_path(story_id: @mytale.story_id, id: @mytale.id), class: "print-link"%>

      <% if is_owner? %>
      <%= link_to "Edit", edit_story_mytale_path(story_id: @mytale.story_id, mytale_id: @mytale.id) %> <%= link_to "Email", email_story_mytale_path(story_id: @mytale.story_id, mytale_id: @mytale.id) %><%= link_to "Delete", story_mytale_path(story_id: @mytale.story_id, mytale_id: @mytale.id), method: :delete %>
    </p>
    <% end %>
  </div>
  <div class="col span_1_of_3">
    <%= image_tag(@image.url) %>
  </div>

  <div class="section">
      <h3>Save for later</h3>
      <% if is_owner? %>
      View this story and others you've created on your <%= link_to "profile page", user_path(current_user.id) %>.
      <% else %>
      <p>
        You can always access this story at:
      </p>
      <%= link_to "#{story_mytale_url(story_id: @mytale.story_id, id: @mytale.id)}", story_mytale_url(story_id: @mytale.story_id, id: @mytale.id) %>
      <% end %>
    </p>
  </div>
</div>